### ISSUE TITLE
Hi, Joe!

### ISSUE THREAD

**Issue by YakovOsipenkov** [Joe12387/overpoweredjs-api#1]
Hi

Access to fetch at 'https://ccorse.overpoweredjs.bot/ccorse' from origin 'https://site.com' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'null' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

GET https://ccorse.overpoweredjs.bot/ccorse net::ERR_FAILED 200 (OK)

SecurityError: Failed to read a named property 'toJSON' from 'Window': Blocked a frame with origin "https://site.com" from accessing a cross-origin frame.

Help plz. Thanks!

**Comment by Joe12387** [comment]
Hi,

Sorry, I did not receive your email. The security error you mention is actually a bot test that takes place if you score 3 or higher. Opening devtools causes CDP to be detected, which is why the request is taking place. If you do not have CDP on, this request will not occur. You can safely ignore the error.

Thanks,
Joe

**Comment by YakovOsipenkov** [comment]
Thanks. I did it! I wrote to you from the mail ya.osipenkov@icloud.com (11.11.2024) on Joe@dreggle.com. Please check SPAM
